crudapp/urls.py
from django.contrib import admin
from django.urls import path
from employee import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('emp', views.emp),  
    path('show',views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
]

employee/models.py
from django.db import models

# Create your models here.
class Employee(models.Model):
    eid = models.CharField(max_length=20)
    ename = models.CharField(max_length=100)
    eemail = models.EmailField()
    econtact = models.CharField(max_length=15)
    class Meta:
        db_table = "employee"

employee/forms.py
from django import forms  
from employee.models import Employee  

# create emplloyee form
class EmployeeForm(forms.ModelForm):  
    class Meta:  
        model = Employee  
        fields = "__all__"

employee/views.py
from django.shortcuts import render, redirect
from employee.forms import EmployeeForm
from employee.models import Employee

# Create your views here.
def emp(req):
    if req.method == 'POST':
        form = EmployeeForm(req.POST)
        if form.is_valid():
            try:
                form.save()
                return redirect('/show')
            except:
                pass
    else:
        form = EmployeeForm()
    return render(req, 'index.html', {'form' : form})

def show(req):
    employees = Employee.objects.all()
    return render(req,'show.html', {'employees': employees})

def edit(req, id):
    employee = Employee.objects.get(id = id)
    return render(req, 'edit.html', {'employee' : employee})

def update(req, id):
    employee = Employee.objects.get(id = id)
    form = EmployeeForm(req.POST, instance = employee)
    if form.is_valid():
        form.save()
        return redirect('/show')
    return render(req, 'edit.html', {'employee' : employee})
def destroy(req, id):
    employee = Employee.objects.get(id = id)
    employee.delete()
    return redirect('/show')

employee/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{employee.id}}">
      {% csrf_token %}
      <div
        class="container w-[600px] mt-10 border-[1px] border-red-500 mx-auto"
      >
        <br />
        <div class="form-group row align-items-center justify-content-center mb-3">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-6">
            <h3>Update Details</h3>
          </div>
        </div>
        <div class="form-group row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Id:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="eid"
              id="id_eid"
              required
              maxlength="20"
              value="{{ employee.eid }}"
            />
          </div>
        </div>
        <div class="form-group row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Name:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="ename"
              id="id_ename"
              required
              maxlength="100"
              value="{{ employee.ename }}"
            />
          </div>
        </div>
        <div class="form-group row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Email:</label>
          <div class="col-sm-4">
            <input
              type="email"
              name="eemail"
              id="id_eemail"
              required
              maxlength="254"
              value="{{ employee.eemail }}"
            />
          </div>
        </div>
        <div class="form-group row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Contact:</label>
          <div class="col-sm-4">
            <input
              type="text"
              name="econtact"
              id="id_econtact"
              required
              maxlength="15"
              value="{{ employee.econtact }}"
            />
          </div>
        </div>
        <div class="form-group row align-items-center justify-content-center mb-3">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <button type="submit" class="btn btn-success">Update</button>
          </div>
        </div>
      </div>
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

employee/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <form method="POST" class="post-form" action="/emp">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="form-group row">
          <label class="col-sm-1 col-form-label"></label>
          <div class="col-sm-4">
            <h3>Enter Details</h3>
          </div>
        </div>
        <div class="row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Id:</label>
          <div class="col-sm-auto">{{ form.eid }}</div>
          <!--khi views gọi đến index thì giá trị của form.eid-->
        </div>
        <div class="row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Name:</label>
          <div class="col-sm-auto">{{ form.ename }}</div>
        </div>
        <div class="row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Email:</label>
          <div class="col-sm-auto ">{{ form.eemail }}</div>
        </div>
        <div class="row align-items-center justify-content-center">
          <label class="col-sm-4 col-form-label">Employee Contact:</label>
          <div class="col-sm-auto">{{ form.econtact }}</div>
        </div>
        <div class="row align-items-center justify-content-center">
          <div class="col-sm-4">
            <button type="submit" class="button">Submit</button>
          </div>
        </div>
      </div>
    </form>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

employee/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Employee Records</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <table class="table table-striped table-bordered table-sm w-75 mx-auto mt-5">
      <thead class="thead-dark">
        <tr>
          <th>Employee ID</th>
          <th>Employee Name</th>
          <th>Employee Email</th>
          <th>Employee Contact</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for employee in employees %}
        <tr>
          <td>{{ employee.eid }}</td>
          <td>{{ employee.ename }}</td>
          <td>{{ employee.eemail }}</td>
          <td>{{ employee.econtact }}</td>
          <td class="">
            <button class="btn btn-warning ">
            <a href="/edit/{{ employee.id }}" 
              ><span class="glyphicon glyphicon-pencil">Edit</span></a
            ></button>
            <button class="btn btn-danger">
            <a href="/delete/{{ employee.id }}">Delete</a>
            </button>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    <br />
    <br />
    <center><a href="/emp" class="btn btn-primary">Add New Record</a></center>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
      crossorigin="anonymous"
    ></script>
  </body>
</html>